package Exercise2.Task3;

import java.util.concurrent.Executor;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class RandomThread implements Runnable {
    RandomResource random;


    public RandomThread(RandomResource random){
        this.random = random;
    }

    public void run(){
        for(int i = 0; i<1; i++){
            try {

                random.randomNumber();
                System.out.println(Thread.currentThread().getName() + " is running");
                Thread.sleep(1);

            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

    }

    public static void main(String[] args) throws InterruptedException{

        RandomResource random = new RandomResource();

        ExecutorService service = Executors.newFixedThreadPool(5);
        for (int i = 0; i < 5; i++) {
            Runnable t11 = new RandomThread(random);
            Thread t1 =  new Thread(t11);
            service.execute(t1);
        }
        service.isTerminated();

        int sum = 0;
        for (int i = 0; i < random.getNumber().size(); i++){
            sum = sum + random.getNumber().get(i);
            System.out.println(random.getNumber().get(i));
        }
        System.out.println("The sum of the numbers generated by the threads is " + sum);

    }
}
